### ISSUE TITLE
Auto complete validates if there's a script set (selected), command treatment doesn't.

### ISSUE THREAD

**Issue by Dantae-Jekins** [farinap5/Venera#20]
Although the completion checks whether a script is set or not when giving suggestions, the command terminal which calls the function itself doesn't. It's possible to list "globals" with a set script (valid, should be added to "p.SSet" suggestions), and also to call the "run" function when there's no script selected, although it deals with the error when calling the function, this implementation is prone to errors and forces the functions to treat them individually.

Fix: Implement two different blocks in the cmd file, one that should function when a script is set and one that shouldn't, preventing script functions to be called with no real set script.

**Comment by Dantae-Jekins** [comment]
Exemplo de problema:
Reload chamável sem script settado
```go
[*]>> reload
[OK]- Freeing memory.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x5e1702]

goroutine 1 [running]:
github.com/yuin/gopher-lua.(*LState).Close(0x0)
        /home/jekins/go/pkg/mod/github.com/yuin/gopher-lua@v1.0.0/state.go:1384 +0x22
venera/src.ReloadScript(0xc0002e7b20)
        /home/jekins/imports/Venera/src/cmds.go:198 +0xb6
venera/src.(*Profile).Execute(0xc0002e7b20, {0xc000134790?, 0x13cf000?})
        /home/jekins/imports/Venera/src/cmds.go:43 +0x365
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000251710)
        /home/jekins/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.6/prompt.go:84 +0x755
venera/src.(*Profile).InitCLI(0xc0002e7b20)
        /home/jekins/imports/Venera/src/initcli.go:33 +0x2bc
venera/src.Start(0x3d23d70a, 0x0)
        /home/jekins/imports/Venera/src/init.go:42 +0x1a5
main.main()
        /home/jekins/imports/Venera/main.go:10 +0x25
exit status 2
make: *** [Makefile:46: run] Error 1```

**Comment by Dantae-Jekins** [comment]
done
